"""create core tables

Revision ID: 68593b5775c1
Revises: 
Create Date: 2026-05-08 12:21:06.957497

"""
from __future__ import annotations

from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68593b5775c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hooks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('matcher', sa.String(length=255), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('doc_path', sa.String(length=512), nullable=True),
    sa.Column('parent_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_parent_plan_id', 'plans', ['parent_plan_id'], unique=False)
    op.create_index('ix_plans_repo', 'plans', ['repo'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('compute_tier', sa.String(length=32), server_default=sa.text("'standard'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('version_strategy', sa.String(length=32), server_default=sa.text("'latest'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo', 'event_type', name='uq_event_triggers_repo_event')
    )
    op.create_index('ix_event_triggers_event_type', 'event_triggers', ['event_type'], unique=False)
    op.create_table('role_hooks',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('hook_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'hook_id', name='pk_role_hooks')
    )
    op.create_index('ix_role_hooks_role_id', 'role_hooks', ['role_id'], unique=False)
    op.create_table('role_skills',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id', name='pk_role_skills')
    )
    op.create_index('ix_role_skills_role_id', 'role_skills', ['role_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_versions_workflow_version')
    )
    op.create_index('ix_workflow_versions_workflow_id', 'workflow_versions', ['workflow_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_plan_id', 'tasks', ['plan_id'], unique=False)
    op.create_index('ix_tasks_repo', 'tasks', ['repo'], unique=False)
    op.create_index('ix_tasks_workflow_version_id', 'tasks', ['workflow_version_id'], unique=False)
    op.create_table('workflow_version_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_version_id', 'step_index', name='uq_workflow_version_steps_index')
    )
    op.create_index('ix_workflow_version_steps_workflow_version_id', 'workflow_version_steps', ['workflow_version_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('expression', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_dependencies_task_id', 'task_dependencies', ['task_id'], unique=False)
    op.create_table('task_prs',
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('branch', sa.String(length=512), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo', 'pr_number', name='pk_task_prs')
    )
    op.create_index('ix_task_prs_task_id', 'task_prs', ['task_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_runs_task_id', 'workflow_runs', ['task_id'], unique=False)
    op.create_index('ix_workflow_runs_workflow_version_id', 'workflow_runs', ['workflow_version_id'], unique=False)
    op.create_table('workflow_run_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_index', name='uq_workflow_run_steps_run_index')
    )
    op.create_index('ix_workflow_run_steps_run_id', 'workflow_run_steps', ['run_id'], unique=False)
    op.create_index('ix_workflow_run_steps_status', 'workflow_run_steps', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_run_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index('ix_events_entity_action', 'events', ['entity_type', 'action'], unique=False)
    op.create_index('ix_events_plan_id', 'events', ['plan_id'], unique=False)
    op.create_index('ix_events_run_id', 'events', ['run_id'], unique=False)
    op.create_index('ix_events_task_id', 'events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_task_id', table_name='events')
    op.drop_index('ix_events_run_id', table_name='events')
    op.drop_index('ix_events_plan_id', table_name='events')
    op.drop_index('ix_events_entity_action', table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_workflow_run_steps_status', table_name='workflow_run_steps')
    op.drop_index('ix_workflow_run_steps_run_id', table_name='workflow_run_steps')
    op.drop_table('workflow_run_steps')
    op.drop_index('ix_workflow_runs_workflow_version_id', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_task_id', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_task_prs_task_id', table_name='task_prs')
    op.drop_table('task_prs')
    op.drop_index('ix_task_dependencies_task_id', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_workflow_version_steps_workflow_version_id', table_name='workflow_version_steps')
    op.drop_table('workflow_version_steps')
    op.drop_index('ix_tasks_workflow_version_id', table_name='tasks')
    op.drop_index('ix_tasks_repo', table_name='tasks')
    op.drop_index('ix_tasks_plan_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_workflow_versions_workflow_id', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index('ix_role_skills_role_id', table_name='role_skills')
    op.drop_table('role_skills')
    op.drop_index('ix_role_hooks_role_id', table_name='role_hooks')
    op.drop_table('role_hooks')
    op.drop_index('ix_event_triggers_event_type', table_name='event_triggers')
    op.drop_table('event_triggers')
    op.drop_table('workflows')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_index('ix_plans_repo', table_name='plans')
    op.drop_index('ix_plans_parent_plan_id', table_name='plans')
    op.drop_table('plans')
    op.drop_table('hooks')
    # ### end Alembic commands ###
